name: "Nieuwe Feature"
description: File a bug report
title: "[Feature]: "
body:
  - type: markdown
    attributes:
      value: |
        Hieronder vul je de nieuwe feature in!
  - type: input
    id: feature
    attributes:
      label: Feature
      description: Wat is de feature in enkel woorden?
      placeholder: ex. De fiets moet 2 geven
    validations:
      required: true
  - type: textarea
    id: feature-detail
    attributes:
      label: Details van Feature
      description: In detail vertel wat er moet gebeuren
      placeholder: Vertel wat er moet gebeuren
    validations:
      required: true
